
project_id = "***REMOVED***"

[functions.upload-client-payment-proof]
verify_jwt = false

[functions.get-client-project]
verify_jwt = false

[functions.submit-payment-proof]
verify_jwt = false

[functions.send-payment-notification]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.lemon-squeezy-webhook]
verify_jwt = false
